name: Write Website to GCS
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'iam.googleapis.com/projects/292324331506/locations/global/workloadIdentityPools/github/providers/github-profider'
        service_account: 'github@latenightearly.iam.gserviceaccount.com'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'public'
        destination: 'dcwcs'